version: '3.1'

services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: loja
      MYSQL_USER: crawler
      MYSQL_PASSWORD: crawler
    volumes:
      - ./db:/var/lib/mysql
    ports:
      - '3306:3306'